package com.example.copilot_project.service;

import com.example.copilot_project.entity.User;
import com.example.copilot_project.exception.InvalidCredentialsException;
import com.example.copilot_project.exception.UserAlreadyExistsException;
import com.example.copilot_project.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * UserService Class
 *
 * Service layer that handles business logic for user management.
 * This layer sits between the Controller and Repository layers.
 *
 * @Service: Marks this class as a Spring service component (business logic layer)
 * @RequiredArgsConstructor: Lombok annotation that generates a constructor with all final fields as parameters
 *                           This enables constructor injection of dependencies
 * @Slf4j: Lombok annotation that generates a logger instance for logging
 *
 * Layered Architecture:
 * Controller (HTTP requests) → Service (Business Logic) → Repository (Database) → Entity (Data Model)
 */

@Service
@RequiredArgsConstructor
@Slf4j
public class UserService {

    /**
     * UserRepository - Data access object for User entity
     * Injected via constructor (Constructor Injection - best practice)
     */
    private final UserRepository userRepository;

    /**
     * PasswordEncoder - Spring Security component for encoding and verifying passwords
     * Injected from Spring's configuration
     */
    private final PasswordEncoder passwordEncoder;

    /**
     * Register a new user
     *
     * This method:
     * 1. Validates that email doesn't already exist
     * 2. Encodes the password using BCrypt
     * 3. Saves the user to the database
     * 4. Logs the registration event
     *
     * @param user User object containing name, email, and plain-text password
     * @return The saved User object (now contains the ID generated by the database)
     * @throws UserAlreadyExistsException if email already exists in database
     *
     * @Transactional: Ensures the entire method is executed as a single database transaction
     *                 If any error occurs, the transaction is rolled back (no partial saves)
     */
    @Transactional
    public User registerUser(User user) {
        log.info("Attempting to register user with email: {}", user.getEmail());

        // Step 1: Check if email already exists
        if (userRepository.existsByEmail(user.getEmail())) {
            log.warn("Registration failed: Email already exists: {}", user.getEmail());
            throw new UserAlreadyExistsException("Email already registered. Please use a different email.");
        }

        // Step 2: Encode the password using BCrypt
        // BCrypt automatically creates a salted hash, making it secure even if database is compromised
        String encodedPassword = passwordEncoder.encode(user.getPassword());
        user.setPassword(encodedPassword);

        // Step 3: Save user to database
        User savedUser = userRepository.save(user);
        log.info("User registered successfully: {}", savedUser.getEmail());

        return savedUser;
    }

    /**
     * Authenticate user login credentials
     *
     * This method:
     * 1. Finds the user by email
     * 2. Compares the provided password with the stored encoded password
     * 3. Returns the user if credentials are valid
     * 4. Throws exception if credentials are invalid
     *
     * @param email User's email address
     * @param plainPassword Plain-text password provided by user
     * @return The authenticated User object
     * @throws InvalidCredentialsException if email not found or password doesn't match
     */
    public User authenticateUser(String email, String plainPassword) {
        log.info("Attempting to authenticate user with email: {}", email);

        // Step 1: Find user by email
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> {
                    log.warn("Authentication failed: User not found with email: {}", email);
                    return new InvalidCredentialsException("Invalid email or password.");
                });

        // Step 2: Compare passwords
        // passwordEncoder.matches(plainPassword, encodedPassword) compares:
        // - plainPassword: The password user entered in login form
        // - encodedPassword: The salted hash stored in database
        // It returns true if they match
        if (!passwordEncoder.matches(plainPassword, user.getPassword())) {
            log.warn("Authentication failed: Invalid password for email: {}", email);
            throw new InvalidCredentialsException("Invalid email or password.");
        }

        log.info("User authenticated successfully: {}", email);
        return user;
    }

    /**
     * Find a user by email address
     *
     * @param email The email address to search for
     * @return User if found, null if not found
     */
    public User findByEmail(String email) {
        return userRepository.findByEmail(email).orElse(null);
    }

    /**
     * Find a user by ID
     *
     * @param id The user ID
     * @return User if found, null if not found
     */
    public User findById(Long id) {
        return userRepository.findById(id).orElse(null);
    }
}

